### PR TITLE
Adds default APT/YUM repositories into filebeat_pkg state

### PR DESCRIPTION
**Pull request by RobRuana**
Adding the package repositories into the `filebeat_pkg` state allows this formula to work "out of the box".

### CODE REVIEW

**Comment by ssplatt** [comment]
The original intent was to relegate all repositories to the [repos-formula](https://github.com/ssplatt/repos-formula). This is mainly because there are many other formulas that use the exact same repos (all of the beats, elasticsearch, logstash, and kibana). If each of those formulas managed the repo separately and were enabled on the same host, the repo block would run multiple times which is not desired.

if you still want to include the repo in each specific formula, i suggest placing it under a toggle and assigning it to false by default to keep the current functionality:
```
#state
{% if filebeat.repo_managed %}
...
{% endif %}

#pillar
filebeat:
  repo_managed: false
```

**Review by ssplatt — CHANGES_REQUESTED** [review]
please place under a toggle

**Comment by cmarzullo** [comment]
I concur with @ssplatt Different orgs may manage their repos differently with pinning or private repos. In the code example above it doesn't parameterize the repos so you'll always be stuck with the elastic repo.

**Comment by RobRuana** [comment]
Thanks for the feedback! I added the `repo_managed` toggle as requested.

I chose to use your `filebeat-formula` for our project because it was the cleanest, most full-featured filebeat formula out there. I didn't realize you also maintained a [repos-formula](https://github.com/ssplatt/repos-formula) for repo management. That's a cool idea, but for our needs a simple toggle does the trick.

I hope you find the updates acceptable 😄

**Comment by ssplatt** [comment]
spec tests for the custom env where the repo is enabled? i have a couple tweaks to apply to get all of the tests to pass in travis-ci but we should be able to see the states pass in the logs, regardless

**Comment by RobRuana** [comment]
I added a test for `repo_managed: True`. Though, as you mentioned, I'm having a hard time getting the tests to run. I am encountering the following error:
```
-----> Installing Serverspec..
       /usr/lib/ruby/2.1.0/rubygems/installer.rb:543:in `ensure_required_ruby_version_met': net-telnet requires Ruby version >= 2.3.0. (Gem::InstallError)
```

However, you do see the state execute successfully:
```
       ----------
                 ID: filebeat_pkgrepo
           Function: pkgrepo.managed
               Name: deb https://artifacts.elastic.co/packages/5.x/apt stable main
             Result: True
            Comment: Configured package repo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
            Started: 21:07:53.875008
           Duration: 4647.465 ms
            Changes:   
              ----------
              repo:
                  deb https://artifacts.elastic.co/packages/5.x/apt stable main
       ----------
                 ID: filebeat_pkg
           Function: pkg.installed
               Name: filebeat
             Result: True
            Comment: The following packages were installed/updated: filebeat
            Started: 21:07:58.523837
           Duration: 4411.011 ms
            Changes:   
              ----------
              filebeat:
                  ----------
                  new:
                      5.6.10
                  old:
       ----------
```

**Comment by RobRuana** [comment]
Also, if you'd prefer to keep the toggle functionality out of your repo altogether, I'm happy to close this pull request and let our forks diverge! No worries 😄

**Comment by ssplatt** [comment]
i updated the tests to use a debian 9 image. the error you were encountering is because the ruby version was too old in debian 8. If you wouldn't mind adding centos to the kitchen configurations too, that would be great.

The tests that are failing in CI are the service running and enabled checks. They pass in vagrant but not in Docker. I haven't figured out why yet but as long as those are the only ones that fail, I'll merge this PR

**Comment by RobRuana** [comment]
Apologies for the delay! I tried adding centos-7.5 to the kitchen configuration, but I kept running into the same outdated ruby version issue that I was seeing with debian-8. Unfortunately, I'm not familiar enough with kitchen to configure additional dependencies.

debian-9 works great though! Thanks for updating that 😄

**Review by ssplatt — APPROVED** [review]
👍

**Pull request merged**
